# Generated by Django 5.1.6 on 2025-02-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supports", "0003_alter_comment_public_id_alter_thread_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="public_id",
            field=models.CharField(default="nCZC4wEASoX73kk4Quu64d", max_length=50),
        ),
        migrations.AlterField(
            model_name="thread",
            name="public_id",
            field=models.CharField(default="nCZC4wEASoX73kk4Quu64d", max_length=50),
        ),
    ]
