# Generated by Django 5.1.6 on 2025-03-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supports", "0006_alter_comment_public_id_alter_thread_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="media",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="public_id",
            field=models.CharField(default="d45dCCHM54X5KzZwEuoFgD", max_length=50),
        ),
        migrations.AlterField(
            model_name="thread",
            name="public_id",
            field=models.CharField(default="d45dCCHM54X5KzZwEuoFgD", max_length=50),
        ),
        migrations.AlterField(
            model_name="thread",
            name="replies",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
