# Generated by Django 5.1.6 on 2025-03-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supports", "0007_alter_comment_media_alter_comment_public_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="has_threads",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="threads",
            field=models.JSONField(default=[], null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="public_id",
            field=models.CharField(default="mAuGuM4uVds9SccLhhW8gS", max_length=50),
        ),
        migrations.DeleteModel(
            name="Thread",
        ),
    ]
