# Generated by Django 5.1.6 on 2025-03-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supports", "0008_comment_has_threads_comment_threads_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="public_id",
            field=models.CharField(default="2ZJrgEdoTgNpoa6rYNCPZC", max_length=50),
        ),
        migrations.AlterModelTable(
            name="comment",
            table="comments",
        ),
    ]
