# Generated by Django 5.1.6 on 2025-03-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supports", "0010_alter_comment_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="public_id",
            field=models.CharField(default="Xrp6PHK4XdYmsNAzS9zaaU", max_length=50),
        ),
        migrations.AlterField(
            model_name="comment",
            name="threads",
            field=models.JSONField(null=True),
        ),
    ]
