# Generated by Django 5.1.6 on 2025-07-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0019_alter_comment_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='has_threads',
        ),
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='fxz6oVfCgFTq4RKsa5JWNa', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='threads',
            field=models.JSONField(default=[]),
        ),
    ]
