# Generated by Django 5.1.6 on 2025-07-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0020_remove_comment_has_threads_alter_comment_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='57tkXAbJmVUeh8QdagdL9P', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='threads',
            field=models.JSONField(default=list),
        ),
    ]
