# Generated by Django 5.1.6 on 2025-07-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0021_alter_comment_public_id_alter_comment_threads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_sub',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='threads',
        ),
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='fBYJZ8vVmoYkgKaMgH3VQy', max_length=50),
        ),
    ]
