# Generated by Django 5.1.6 on 2025-07-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0022_remove_comment_is_sub_remove_comment_threads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='QZBLJh5BcxDvWSNRwq5Fyn', max_length=50),
        ),
    ]
