# Generated by Django 5.1.6 on 2025-02-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_profile_communities_alter_profile_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="public_id",
            field=models.CharField(default="LWDTQougcn2FavZrPWuXC7", max_length=50),
        ),
    ]
