# Generated by Django 5.1.6 on 2025-03-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_alter_profile_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="public_id",
            field=models.CharField(default="Xrp6PHK4XdYmsNAzS9zaaU", max_length=50),
        ),
    ]
