# Generated by Django 5.1.6 on 2025-06-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_alter_profile_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="public_id",
            field=models.CharField(default="PM7gE3Sgp3RYcmSZ5AZHV2", max_length=50),
        ),
    ]
