# Generated by Django 5.1.6 on 2025-07-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_profile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='Fa8CFBCYmbhdJmRfYas5dj', max_length=50),
        ),
    ]
