# Generated by Django 5.1.6 on 2025-07-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_profile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='fxz6oVfCgFTq4RKsa5JWNa', max_length=50),
        ),
    ]
