# Generated by Django 5.1.6 on 2025-07-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_profile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='QZBLJh5BcxDvWSNRwq5Fyn', max_length=50),
        ),
    ]
