# Generated by Django 5.1.6 on 2026-06-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_community_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='public_id',
            field=models.CharField(default='P7pbiZzjSzY54MPyv6qpPS', max_length=50),
        ),
    ]
