# Generated by Django 5.1.6 on 2025-03-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0009_alter_community_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="public_id",
            field=models.CharField(default="UFGsZ7tRaLhKqKeTJgDfWS", max_length=50),
        ),
    ]
