# Generated by Django 5.1.6 on 2025-06-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_alter_community_admins_alter_community_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='admins',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='public_id',
            field=models.CharField(default='GvSz6pLERaKBYiXgACzeX3', max_length=50),
        ),
    ]
