# Generated by Django 5.1.6 on 2025-07-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_alter_community_admins_alter_community_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='public_id',
            field=models.CharField(default='Ce2Q4VyEnpV4GBUxeZ5kPv', max_length=50),
        ),
    ]
