# Generated by Django 5.1.6 on 2025-07-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_alter_community_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='public_id',
            field=models.CharField(default='57tkXAbJmVUeh8QdagdL9P', max_length=50),
        ),
    ]
