# Generated by Django 5.1.6 on 2025-07-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_alter_community_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='public_id',
            field=models.CharField(default='fBYJZ8vVmoYkgKaMgH3VQy', max_length=50),
        ),
    ]
