# Generated by Django 5.1.6 on 2025-07-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_alter_community_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='public_id',
            field=models.CharField(default='mcwE5GE2EWQ6MWjyLwWvpU', max_length=50),
        ),
    ]
