"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    'version': 1, # The version of the logging configuration schema.
    'disable_existing_loggers': False, # Keep existing loggers enabled.

    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'standard': {
            'format': '[{levelname}] {asctime} {module}.{funcName}:{lineno} - {message}',
            'style': '{',
        },
    },

    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },

    'handlers': {
        'console': {
            'level': 'INFO', # Log INFO and above to console
            'filters': ['require_debug_true'], # Only show on console when DEBUG is True
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_info': {
            'level': 'INFO', # Log INFO and above to info.log
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'info.log'),
            'maxBytes': 1024*1024*5, # 5 MB
            'backupCount': 5, # Keep 5 backup logs
            'formatter': 'standard',
            'filters': ['require_debug_false'], # Only log to file when DEBUG is False
        },
        'file_error': {
            'level': 'ERROR', # Log ERROR and above to error.log
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'error.log'),
            'maxBytes': 1024*1024*5, # 5 MB
            'backupCount': 5, # Keep 5 backup logs
            'formatter': 'verbose',
            'filters': ['require_debug_false'], # Only log to file when DEBUG is False
        },
        'mail_admins': {
            'level': 'ERROR', # Email admins on ERROR and above
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'], # Only email when DEBUG is False
        },
    },

    'loggers': {
        'django': { # The default Django logger
            'handlers': ['console', 'file_info'],
            'level': 'INFO',
            'propagate': True, # Allow logs to propagate to root logger
        },
        'django.request': { # Logs requests, including 4xx and 5xx errors
            'handlers': ['file_error', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False, # Don't propagate to avoid duplicate emails
        },
        'my_app': { # Custom logger for your application
            'handlers': ['file_info', 'file_error'],
            'level': 'INFO', # Set a default level for your app
            'propagate': False, # Don't propagate to root logger if handled here
        },
        '': { # The root logger
            'handlers': ['console', 'file_info', 'file_error'],
            'level': 'WARNING', # Default level for anything not explicitly configured
            'propagate': True,
        },
    },
}


load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("project_secret_key")

# SECURITY WARNING: don't run with debug turned on in production!
debug_var = os.getenv("debug")
debug_bool = False  if debug_var == "false" else True
DEBUG = debug_bool

ALLOWED_HOSTS = [os.getenv("allowed_host")] if debug_bool else [
    "http://localhost:3000", 
    os.getenv("allowed_host")
]


# Application definition
default_apps = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]
third_party_apps = ["rest_framework", "rest_framework.authtoken", "corsheaders"]
custom_apps = ["supports", "account", "discussion", "community", "analytics"]
INSTALLED_APPS = default_apps + third_party_apps + custom_apps
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
# CORS_ALLOW_ALL_ORIGINS = debug_bool
CORS_ALLOWED_ORIGINS=[
    "http://localhost:3000", 
    os.getenv("allowed_cors_origin")
]
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication"
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
}


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
 
WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"
CHANNEL_LAYERS = {
    "default":{
        "BACKEND":"channels.layers.InMemoryChannelLayer",
        # 'CONFIG': {
        #     "hosts": [('127.0.0.1', 6379)], # Or your Redis host/port
        # },
    }
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
local_db=  {"default":{
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("db_name"),
        "USER": os.getenv("db_user"),
        "HOST": os.getenv("db_host"),
        "PASSWORD": os.getenv("db_password"),
    }}

deployment_db = {
    "default":dj_database_url.config(default = os.getenv("db_url"),conn_max_age=600)
}
# DATABASES = deployment_db
DATABASES = local_db if debug_bool else deployment_db



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Configuring loggin
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
#             'datefmt' : "%d/%b/%Y %H:%M:%S"
#         },
#         'simple': {
#             'format': '%(levelname)s %(message)s'
#         },
#     },
#     'handlers': {
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': 'mysite.log',
#             'formatter': 'verbose'
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers':['file'],
#             'propagate': True,
#             'level':'DEBUG',
#         },
#         'MYAPP': {
#             'handlers': ['file'],
#             'level': 'DEBUG',
#         },
#     }
# }