# Generated by Django 5.1.6 on 2025-02-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="public_id",
            field=models.CharField(default="Uuh3ya78Kk6sKqu4WhhLqz", max_length=50),
        ),
    ]
