# Generated by Django 5.1.6 on 2025-02-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0005_discussion_members_alter_discussion_public_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discussion",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="discussion",
            name="public_id",
            field=models.CharField(default="WCyZZzz78ZwqhJErKT9jKp", max_length=50),
        ),
    ]
