# Generated by Django 5.1.6 on 2025-03-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0006_rename_name_discussion_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="public_id",
            field=models.CharField(default="d45dCCHM54X5KzZwEuoFgD", max_length=50),
        ),
    ]
