# Generated by Django 5.1.6 on 2025-03-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0008_alter_discussion_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="public_id",
            field=models.CharField(default="2ZJrgEdoTgNpoa6rYNCPZC", max_length=50),
        ),
    ]
