# Generated by Django 5.1.6 on 2025-07-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0017_alter_discussion_members_alter_discussion_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='public_id',
            field=models.CharField(default='Ce2Q4VyEnpV4GBUxeZ5kPv', max_length=50),
        ),
    ]
